language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- export DOCKER_HOST="$HOST_NAME"
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l

script:
- docker build -t kuribohw/se234-lab11-client .
- docker push kuribohw/se234-lab11-client
- docker pull kuribohw/se234-lab11-client
service: docker
env:
  global:
  - secure: sS3FjxKDPXx2wNun1W5/h0ONa1JEe5B0Krg2a4/oi+GWsRYylRwjxF4xLRa2NvFzd8uANn/inkqMImfaXhJtQHunzoPnc6jxcSNcqjdFFngFy4E9vCDFw0zY81W9anKliNdyiqfx7SB0oQVOo2+wMY/ESziYZNNsmC1DryIdCYJsnKbzosiq+NAKG6tG/qgVGs/DWzh1pesOqLY8ImIf9I1Rpj/98M3T+bMprxysfRBZY0k4iOrcfVlugDodcLFsm1BuiC2AuzMbBGZ7Zy46v/Y9bOjFdkXoWfale9w8BtIzTmYgsmgtbMUFQ9rpyJ/bcjosqlECXZMR0O2GNSAjX4WqxSeXt/7MAuwcgULtUjE+g03pKCpZ6v5nYw2zk7Rq1XGzxnTBO8q3Iap8IgKxe0LcV3yh4ygIGCGJdlhbcH3Ao6ZyCCp1DWbh+7RQADEOClF+jr0KIjSZ1WQOEP1jpY1Nb5VDJHXRQ0iRteo25dBwTga3YYQfO4DHi7cFqj5Gus865HQiVaE2/0vv4e1fvkl3yfq5Izi+ifI1BMzZEKTE8PhKqV44GIJmEXNa0hsMec9ABq1X5n3tXwa1e0xcZBRY5yqpz5TflQzRSGv2GFdOHq+3SdSGeor3W8R4O2bKjc3dyU/GZDmuKWHAGpjf9tdMXGphbcjtVVNdY0kcR80=
  - secure: u1jY858HGPBDeILNO+C/aK6ZiL8G5B4jKU6VWyFeOX/KJpzbj7+itm0j5JOrVouF0Bs7XbGSCQ1kDZjN0w5mMSzOZ6ngeViThF7BUTs/rYN09kzxlj40a0xkFJD7ruLxdJ1/pdrMfDS6w0kTJFE4HbDTihuEMiNF/AfExywsIlHH6KauaE94YGcd6k2HEdj9FPvZmSMJbY7IGCiOK/Z4v6N33Bc62Xa1d0HG8yt2HkUeo4/HPLL1aDkKg6Kl8k4cxcblPbKXdUp5AelodY8RIWpM1Hk346e7wQNU/ayx1LRV4gk10hCplqYVHqpanY8RcXysuEZUs1sve8KvHlq2qzRFBjSj7LnVtWj8fCFdFODrqRK1BrWHD1C3vqKAYoZAP1fX/+z6p6u0z5qPVTgKqwFUtrGAwC+ZLpAHW3JJ6OMToRbSguMLzUTMs6D9XMlhdaJfeWPdVRSyi15Ix+8rOLmujs7oBnCbdJIOVeq5ns7tgLRD6drLYOjuK77rzWNAFJwji+wsU9lmf2roqQUrrfLeqqrZTVJvSPqdTj0d7JHPhuxFNxzl+XQhM5bdVhrwEl34F/54Rwv3x5qE1d0dUgFqDdnOH3z1vnPScYtIYwXOeu2PhKgo9ex9lrEZvDummbK1GtHPcd8do8t/7eLtIYrCZjTAeLDpFcnWp4l9DeM=
  - secure: wZfLDLfIQQqscQv00Y/y4qepJ5UrqEf9O/yqGowbFAeRyGAegiJcYRkFvyF1lwRGYiBKmg3ejMND8H5K/34juoXP2rDWpsCVlKzV6MsesD77JfTDALkPFftl5o5IkpDUo+J0Qgo562+w5l/sN5+prVsZ06FmflJgSbj2wixiFceA8uusk+CMGpT8Jf4jZKzqpI0gqhvYm8Re+yt70OJe2tQkWhqjEBDgKhSmcJOj6+68AGxoUaW3eImZLpIEeiOyBzIZd6DNSVmn3s9W/66LZxSmJygTI9GVTXX19aRkkbGV+/4+JEOiL/EZFEPsySg5ZPVzHTtyNC6beOWcAjn/JShS+WHta87OvrWnj9iK2vmqA2BCbwjhJ03L22Z0FSKg1bMPw3bdz+n+f97ovCY0WNZihqUxFZf21ac6lISA3KZhwM/yBSfvrNrqjQEZXmGl2+vGnYWKWRmxscR2hPP8ssxeXBy73DXKLVb3XJGA/6kZ61vRWlGUR1PoKOeDDOhhtucCvAlqYYbIv2+rRcBWoOdesuC+NL5OGRfiF9jIQeg5BwrLVEKLZgwS9A3WlLhxS+cKeZ4FvhP+svc9bvmSqeMOQe+oA+fPTGbbE955MHLBknJuA39UTzBGVRpMIQbekAXCYh/HdD6xYphcNqs50aXhM3yY9Yx+MgO1ol7YIPQ=
